import CoreBluetooth
import Foundation

/// One Sophon board.
///
/// Deliberately split from ``SophonHub``: an app gets exactly one
/// `CBCentralManager`, so it cannot live on a per-device object. Keeping
/// per-device state here means views bind to a device rather than to a global,
/// and a second board needs no restructuring.
@MainActor
@Observable
final class SophonDevice: Identifiable {
    enum State: Equatable {
        case discovered
        case connecting
        case connected
        case disconnected(reason: String?)

        var isConnected: Bool { self == .connected }
    }

    /// `CBPeripheral.identifier` — generated by iOS, stable per phone, but
    /// different on a different phone. Not the board's own identity.
    let id: UUID
    let peripheral: CBPeripheral

    /// From the scan-response name, e.g. `Sophon-A3F2`. This *is* the board's
    /// own identity, derived from its FICR chip id.
    var displayName: String

    var state: State = .discovered

    /// Smoothed signal strength in dBm, or nil if none has ever been observed.
    ///
    /// A mean rather than the newest sample. RSSI swings several dB between
    /// consecutive advertisements, and once `SophonHub` turns on duplicate
    /// reporting (#235) those arrive tens of times a second, so the raw value is
    /// unreadable. The mean is also the better input for a `TX power - RSSI`
    /// distance estimate, which is what the field is ultimately for.
    ///
    /// Fed from two sources, and it cannot tell them apart -- deliberately.
    /// Advertisements carry one via `didDiscover`; a connected board is polled
    /// with `readRSSI()` (#237), because a Sophon is `CONFIG_BT_MAX_CONN=1` and
    /// stops advertising the moment it is taken. Both are the central's own
    /// receive strength for the same radio, so one smoothing path is right.
    ///
    /// What it does NOT say is how recently it was measured. Ask ``rssiReading(asOf:)``
    /// for that: polling runs only while the viewer role is on air, and a link can
    /// go quiet while still reading as connected.
    private(set) var rssi: Int?

    /// When the newest sample backing ``rssi`` arrived, or nil if none has.
    ///
    /// `@ObservationIgnored` for the reason ``lastSeenAt`` is: it is rewritten on
    /// every sample, which with duplicate reporting on is tens of times a second,
    /// and no view should redraw on that. Both readers sit inside a
    /// `TimelineView`, which re-reads on its own clock whether or not the value
    /// is observable (#261).
    @ObservationIgnored private(set) var rssiAt: Date?

    /// Recent samples backing ``rssi``, newest last.
    ///
    /// Bounded by **age as well as count**, which the count alone could not do
    /// once #237 added the connected source. The two arrive three orders of
    /// magnitude apart -- tens per second from advertisements, one per second while
    /// connected -- so a fixed 8-sample window spans 0.3 s in one case and 8 s in
    /// the other. Eight seconds cannot follow a tablet being walked away from a
    /// board, which is the check #237 exists to make possible.
    ///
    /// Ageing out also settles what happens across a disconnect, with no
    /// disconnect hook: samples describing the old link expire on their own, so a
    /// reconnect from somewhere else starts its mean from its own first reading
    /// instead of blending into the old one.
    @ObservationIgnored private var rssiSamples: [(value: Int, at: Date)] = []
    private static let rssiWindow = 8
    private static let rssiWindowSpan: TimeInterval = 4

    /// Beyond this, a reading describes the past rather than the present.
    ///
    /// Longer than ``rssiWindowSpan`` on purpose: at the 1 s poll several
    /// consecutive reads have to go missing -- or the link has to have gone quiet
    /// -- before the UI says so, so a late callback cannot flicker the label.
    ///
    /// Deliberately the same 5 s as ``interruptionThreshold``, and now measured
    /// from the same evidence: since ``ingestConnectedRSSI`` credits a reading to
    /// `lastFrameAt`, this row and the State row go stale together on a link that
    /// dies, rather than contradicting each other for the whole supervision
    /// window.
    static let rssiStaleAfter: TimeInterval = 5

    /// A reading from an advertisement, via `didDiscover`.
    ///
    /// **127 means "no reading", not a reading of 127.** It is Core Bluetooth's
    /// unavailable sentinel, and it must not blank a good value: with duplicate
    /// reporting on, one sentinel among tens of samples a second was enough to
    /// make the whole row flicker out of existence. Same latching rule as
    /// `displayName` and `identity` -- a callback carrying nothing may not erase
    /// what an earlier one carried.
    ///
    /// The callback *is* the reception here, so the sample is credited to now.
    func ingestRSSI(_ sample: Int) {
        ingestRSSI(sample, measuredAt: Date())
    }

    /// A reading from `readRSSI()` over an established link (#237).
    ///
    /// Credited to the last packet this app can **prove** arrived, not to the
    /// moment the reply landed -- which is the difference between reporting a
    /// measurement and reporting that we asked for one.
    ///
    /// HCI `Read_RSSI` returns the strength of the controller's *last received
    /// packet*. The controller keeps that value and has no way to add "and that
    /// was a minute ago". Meanwhile `peripheral.state` stays `.connected` for the
    /// whole supervision window after a board dies. So stamping the reply time
    /// would leave the RSSI row looking freshly measured for the entire dead
    /// window, while the State row two lines above it read `Stalled` -- two rows
    /// in one section giving opposite accounts of the same peripheral, and #237's
    /// own defect rebuilt in a new place. Frozen-and-looks-live was the bug; the
    /// fix must not be refreshed-by-asking-and-looks-live.
    ///
    /// `lastFrameAt` is a *conservative* floor. The controller also measures empty
    /// PDUs that never reach this app, so a real reading may be fresher than this
    /// claims -- but on a healthy link frames arrive at tens per second, so the
    /// gap is negligible, and being late is the safe direction.
    func ingestConnectedRSSI(_ sample: Int) {
        ingestRSSI(sample, measuredAt: lastFrameAt ?? connectedAt ?? Date())
    }

    /// - Parameters:
    ///   - sample: raw dBm.
    ///   - measuredAt: when the packet this reading describes actually arrived.
    private func ingestRSSI(_ sample: Int, measuredAt: Date) {
        guard sample != 127 else { return }

        let now = Date()

        // A reading describing a packet older than the window is not news. Drop
        // it rather than admit it: on a dead link this is what stops `rssiAt`
        // advancing, so the age climbs and the row admits it stopped measuring.
        //
        // It also keeps the window non-empty. The freshly appended sample always
        // survives the prune below, so the mean never divides by zero -- which
        // would produce NaN and trap on the conversion to Int.
        guard now.timeIntervalSince(measuredAt) <= Self.rssiWindowSpan else { return }

        rssiSamples.append((sample, measuredAt))
        rssiSamples.removeAll { now.timeIntervalSince($0.at) > Self.rssiWindowSpan }
        if rssiSamples.count > Self.rssiWindow {
            rssiSamples.removeFirst(rssiSamples.count - Self.rssiWindow)
        }
        rssiAt = measuredAt

        let mean = Int((Double(rssiSamples.reduce(0) { $0 + $1.value }) / Double(rssiSamples.count)).rounded())
        if mean != rssi { rssi = mean }
    }

    /// Whether the three link-parameter rows belong on screen at all.
    ///
    /// Deliberately **not** time-dependent, so it can gate from outside a
    /// `TimelineView`. A `TimelineView` is always exactly one List row, so a
    /// branch that renders nothing has to sit outside one or it becomes a blank
    /// cell with separators (#237).
    ///
    /// Gated on a **positive** answer, not on "not yet known". An earlier version
    /// admitted `nil` here, reasoning that waiting is what is happening -- but
    /// `nil` means characteristic discovery has not returned, so every simulator
    /// and every pre-#224 board inserted three `Reading…` rows and removed them
    /// again one round trip later. That is #263's own complaint inverted, and
    /// `Reading…` was not even true in that window: no read had been issued yet.
    /// It also matches the requirement literally -- *while connected with the
    /// characteristic discovered but no value yet*.
    ///
    /// **Not gated on the link being up.** Whether this peripheral *has* the
    /// characteristic is a fact about the peripheral, so once enumerated the rows
    /// keep their place and say what is going on -- `Available while connected`
    /// while there is no link, matching the transmit counters directly below.
    ///
    /// An earlier build hid them on disconnect, to stop the previous session's
    /// numbers sitting under a `Released` state row asserting an interval for a
    /// link that no longer exists. That problem is real -- nothing clears
    /// `linkParams` on disconnect, deliberately, since that persistence is what
    /// keeps the rows from vanishing across `beginSession()`'s reset -- but
    /// hiding the rows is the wrong half to fix. It is #263's own complaint: a
    /// row that disappears cannot explain itself. The stale values are suppressed
    /// by ``linkParamsReading(asOf:)`` returning `offline` instead.
    var showsLinkParams: Bool {
        offersLinkParams == true || linkParams != nil
    }

    /// What those rows should read, once ``showsLinkParams`` says they belong.
    enum LinkParamsReading: Equatable {
        case values(LinkParams)
        case reading
        /// The read never came back and the link has gone quiet.
        case notResponding
        /// No link to have parameters for. Says so rather than showing the last
        /// connection's figures, which iOS is free to have changed since (#224).
        case offline
    }

    /// - Note: `notResponding` exists for the reason the transmit counters give
    ///   for theirs (#242): *a read that never returns is an answer, and
    ///   presenting it as an ongoing wait is the same omission as a green dot
    ///   with no data behind it.*
    ///
    ///   Measured from ``linkParamsRequestedAt`` -- the read itself -- and not
    ///   from `linkStatus`, which describes the motion stream and can be
    ///   perfectly healthy while this particular read fails every time.
    func linkParamsReading(asOf now: Date) -> LinkParamsReading {
        // Checked before the values, so a disconnect cannot leave the previous
        // session's interval on screen looking current.
        guard state.isConnected, hasSession else { return .offline }
        if let linkParams { return .values(linkParams) }
        guard let since = linkParamsRequestedAt,
              now.timeIntervalSince(since) > Self.interruptionThreshold else {
            return .reading
        }
        return .notResponding
    }

    /// Records that a Link Params read has been issued. Idempotent within a
    /// session, so a repeated poll cannot keep pushing the timeout out.
    func noteLinkParamsRequested() {
        guard linkParamsRequestedAt == nil else { return }
        linkParamsRequestedAt = Date()
    }

    /// How long ago the packet behind ``rssi`` arrived, or nil if there is none.
    func rssiAge(asOf now: Date) -> TimeInterval? {
        rssiAt.map { now.timeIntervalSince($0) }
    }

    /// The RSSI row's text and whether it describes the past.
    ///
    /// **One function returning both, deliberately.** A separate label and
    /// staleness flag can disagree -- and the disagreement they produce is an
    /// ageless, confident-looking number in stale styling, which is the precise
    /// thing #237 exists to prevent. Two functions sharing an invariant are only
    /// as safe as the next edit; one function cannot drift from itself.
    ///
    /// A remembered value must not read like a measured one -- the same argument
    /// that produced `Not reported` in #230 and `Released` in #233. Before #237
    /// this row sat perfectly still for the whole of a connected session, and
    /// looked more trustworthy for it.
    func rssiReading(asOf now: Date) -> RSSIReading? {
        guard let rssi else { return nil }

        // No timestamp at all is treated as stale, not as fresh: an unaged
        // reading is an unverified one.
        guard let age = rssiAge(asOf: now) else {
            return RSSIReading(label: "\(rssi) dBm", isStale: true)
        }
        guard age > Self.rssiStaleAfter else {
            return RSSIReading(label: "\(rssi) dBm", isStale: false)
        }
        return RSSIReading(label: "\(rssi) dBm · \(Self.ageText(age)) ago", isStale: true)
    }

    struct RSSIReading: Equatable {
        let label: String
        let isStale: Bool
    }

    /// Coarsens with age. `3612s ago` is a worse answer than `over an hour ago`
    /// in a caption someone glances at, and the extra precision is not real
    /// information at that scale.
    private static func ageText(_ age: TimeInterval) -> String {
        switch age {
        case ..<60: return "\(Int(age.rounded()))s"
        case ..<3600: return "\(Int(age / 60))m"
        default: return "over an hour"
        }
    }


    /// The user has deliberately let this board go, so auto-connect must leave it
    /// alone until they say otherwise.
    ///
    /// Without this a manual disconnect would survive about a second: auto-connect
    /// re-fires from `didDiscover` for anything `.disconnected`, and a Sophon
    /// advertises continuously, so the button would look broken.
    ///
    /// **In-memory by design — not persisted** (#233). A relaunched app connects
    /// again, as it always has. Persisting it would mean a board that silently
    /// refuses to connect after a relaunch with no visible cause, which is the same
    /// confusion the control exists to remove. `SophonHub` uses no
    /// `CBCentralManagerOptionRestoreIdentifierKey`, so there is no background
    /// relaunch that could carry a stale value past the process it belongs to.
    ///
    /// Survives `resetLinkStats()` deliberately: it is a statement about the user,
    /// not about the session.
    var isReleasedByUser = false

    /// When an advertisement from this board was last seen.
    ///
    /// Only meaningful while the scan is reporting duplicates, which `SophonHub`
    /// turns on precisely when some device is released (#235). With duplicates
    /// off — the normal case — iOS consolidates repeat sightings into a single
    /// discovery event, so this would be stamped once and never move.
    /// **Not observable, deliberately (#261).** A fresh `Date` is written on every
    /// advertisement, and while anything is released duplicate reporting makes
    /// that tens of times a second — so an observable write here invalidated the
    /// device's row and its open detail view at advertisement rate, in exactly the
    /// hand-off scenario duplicates exist for. No equality guard can help, since
    /// the value genuinely differs each time.
    ///
    /// Nothing needs the notification. The sweep reads this from the model on its
    /// own 1 s tick, and the only view path is `linkStatus(asOf:)`, which is
    /// always called inside a `TimelineView` that re-evaluates every second and
    /// reads the current value regardless. The state change that views care about
    /// is published through `isStaleReleased`, which the sweep sets.
    @ObservationIgnored var lastSeenAt: Date?

    /// How long a released board may go unheard before it is treated as gone.
    ///
    /// The board advertises at `BT_LE_ADV_CONN_FAST_1`, tens of times a second,
    /// and duplicate reporting is on whenever anything is released — so a free
    /// board produces hundreds of callbacks inside this window and total silence
    /// is unambiguous. Long enough to absorb iOS scan scheduling and radio
    /// contention; short enough that handing a board to another tablet does not
    /// feel like a hang.
    ///
    /// Deliberately NOT `interruptionThreshold`, which is 5 s and tuned for a
    /// ~52 Hz frame stream. Different signal, different scale.
    static let releasedSilenceThreshold: TimeInterval = 15

    /// A released board that has not been heard from inside the threshold.
    ///
    /// Means "not reclaimable right now" — another central has taken it, or it is
    /// powered off, or out of range. The app cannot tell those apart, and does not
    /// claim to.
    ///
    /// **Stored, not computed at render time.** It is a function of elapsed time,
    /// and a view cannot observe the clock: once a board goes quiet nothing about
    /// this object changes, so a body that called `Date()` itself would never be
    /// re-evaluated and the UI would sit on the last answer forever. `SophonHub`'s
    /// sweep re-evaluates this every second, and because it is `@Observable` the
    /// views that read it redraw when it flips.
    private(set) var isStaleReleased = false

    /// Recomputes ``isStaleReleased``. Called by the sweep, not by a view.
    func evaluateStaleness(asOf now: Date = Date()) {
        let stale: Bool
        if !isReleasedByUser || isHeld {
            stale = false
        } else if let lastSeenAt {
            stale = now.timeIntervalSince(lastSeenAt) > Self.releasedSilenceThreshold
        } else {
            stale = true
        }

        // Only on change. Observation notifies on every assignment, equal or not,
        // so writing this once a second for every device would redraw the whole
        // list once a second for nothing.
        if stale != isStaleReleased { isStaleReleased = stale }
    }

    /// Whether the app is holding this board's single connection slot, or trying
    /// to. The connect/disconnect control is a function of exactly this.
    ///
    /// `.connecting` counts as held, so the control offers *Release* rather than
    /// being disabled. That is deliberate and contradicts #233's checklist, which
    /// said to disable it while connecting: an outstanding `connect()` on iOS
    /// never times out — the comment in `SophonHub.suspend()` is there because of
    /// it — so disabling would strand a device that is stuck acquiring, with no
    /// way out but killing the app. `cancelPeripheralConnection` cancels pending
    /// requests as well as live links, so *Release* is meaningful here.
    var isHeld: Bool { state == .connected || state == .connecting }

    /// What the peripheral advertises about itself, or nil if never observed.
    ///
    /// Nil is **normal**, not a fault: an iOS peripheral cannot advertise
    /// manufacturer data at all, so every simulator reads this way permanently,
    /// as does any board not yet reflashed. Display-only — nothing may branch on
    /// it, least of all whether to connect.
    ///
    /// Deliberately absent from `resetLinkStats()`: its lifetime is the
    /// advertisement, not the session. `beginSession()` records what happens when
    /// that distinction is missed: `attMTU` was cleared by the reset and silently
    /// dropped its row until it was re-established there.
    var identity: SophonIdentity?

    /// The connection parameters the peripheral reports iOS granted, or nil if the
    /// characteristic has not been read yet — or the peripheral does not offer it,
    /// which is every board on firmware older than #224 and every simulator.
    ///
    /// **Session-scoped**: cleared by `resetLinkStats()`, unlike `identity` and
    /// `txPower`. These describe *this connection*, so carrying them across one
    /// would be asserting an interval that a reconnect may well have changed —
    /// the same lifetime question `attMTU` answers the same way.
    var linkParams: LinkParams?

    /// Whether this peripheral offers the Link Params characteristic (#224), or
    /// nil while characteristic discovery is still outstanding.
    ///
    /// **Three states, not two**, because "not yet known" and "never going to
    /// answer" need different words on screen. A simulator and any board older
    /// than #224 have no such characteristic and will not grow one; a board that
    /// has it is a second or two away from answering. Collapsing those into one
    /// absent row is what #263 is about.
    ///
    /// **Latched, not session-scoped** -- see `resetLinkStats()`. It describes the
    /// peripheral's GATT database rather than one connection, and clearing it on
    /// reset made the rows flash in and out on every simulator connect.
    var offersLinkParams: Bool?

    /// When the first Link Params read of this session was issued, or nil if
    /// none has been.
    ///
    /// This is what makes ``LinkParamsReading/notResponding`` mean what its label
    /// says. An earlier version inferred it from ``linkStatus`` being `.stalled`,
    /// which is a statement about the **motion notify stream** and is independent
    /// of whether this read came back: a board that returns an ATT error for this
    /// handle, or a payload that is not exactly 8 bytes, keeps streaming frames
    /// at 50 Hz while never answering -- so the rows would have said `Reading…`
    /// forever, which is the precise case the state was added for.
    ///
    /// Set once per session, not per poll. `refreshStats` re-issues the read
    /// every 2 s while the detail view is open, and refreshing this on each one
    /// would mean the timeout could never expire.
    private(set) var linkParamsRequestedAt: Date?

    /// Every advertisement key seen from this peripheral, accumulated.
    ///
    /// A union rather than the latest packet's, because iOS splits advertisement
    /// and scan response across callbacks and a single one is not the whole
    /// picture. Surfaced only when it contains something unexpected — see
    /// `SophonProtocol.expectedAdvertisementKeys` (#246).
    var advertisementKeys: Set<String> = []

    /// Advertised TX power in dBm, from the standard AD type. Signed.
    var txPower: Int?

    // Link health. These are in the skeleton rather than deferred because they
    // are what turn "does it still work with 4 boards?" into an observation
    // instead of a guess (#211).
    var framesReceived: Int = 0
    /// Holes in the peripheral's sequence numbering, on a live stream.
    ///
    /// **A gap says a frame is missing and nothing about where it went** — which
    /// is why the row is labelled "Gaps in sequence" rather than "Lost on link"
    /// (#247). Attribution happens in `lostOnAir`, which subtracts the frames the
    /// peripheral itself refused to send; on an iOS-to-iOS link essentially all
    /// of these turn out to be refusals, so nothing was lost on any link.
    ///
    /// Excludes anything missed while this app was not listening — see
    /// `interruptions`.
    var seqGaps: Int = 0
    /// Times the stream resumed after a hole too large to be loss. Surfaced
    /// separately rather than silently discarded: "gaps 0, interruptions 3"
    /// says more than either number alone, and hiding the interruption would
    /// make a suspended app look like a flawless link.
    var interruptions: Int = 0
    /// Frames unaccounted for across those interruptions. Not losses, but not
    /// nothing either — this is the data the app did not see.
    var framesDuringInterruptions: Int = 0
    /// Times the peripheral restarted **without the link dropping**, detected
    /// from `t_ms` running backwards.
    ///
    /// Not a count of peripheral restarts in general, which is why it is not
    /// named for one. A board reset loses the SoC's connection state, so it
    /// comes back as a reconnect and never reaches the detector -- measured at
    /// 0 across repeated resets. See the note in `ingest`.
    var restartsWithoutDisconnect: Int = 0
    var lastFrame: MotionFrame?
    var lastFrameAt: Date?

    /// Negotiated on connect, logged rather than assumed on both sides.
    ///
    /// Expect **23 from a board**, which does not negotiate up. An iOS peripheral
    /// is another matter: measured at **~515** iOS-to-iOS, which `PROTOCOL.md`
    /// calls the figure mattering most to #211. A large value here is not a fault
    /// — an earlier version of this line said only "expect 23", which made the
    /// docs look wrong rather than the assumption.
    var attMTU: Int?

    /// The board's own transmit counters, read over the stats characteristic.
    /// Cumulative since the *board's* boot, so they do not reset when this
    /// connection does — which is why `txStatsAtConnect` is kept alongside.
    var txStats: TxStats?
    /// Snapshot taken on connect, so the UI can show movement during this
    /// session rather than a total that is mostly historical.
    var txStatsAtConnect: TxStats?
    var txStatsAt: Date?
    /// `seqGaps` as it stood when the most recent stats read landed.
    ///
    /// Exists so `lostOnAir` can subtract two counts covering the SAME window.
    /// `seqGaps` advances as frames arrive; `noBuffer` only refreshes on the 2 s
    /// poll, so differencing the live one against the stale one measures the poll
    /// interval rather than the link (#247).
    private var seqGapsAtStatsRead: Int = 0

    private var previousFrame: MotionFrame?
    /// Set when iOS reports the app left the foreground, cleared by the next
    /// frame that arrives. Any gap spanning it is an interruption regardless of
    /// how brief it was -- which is what elapsed time alone cannot tell you.
    private var wasSuspended = false

    init(peripheral: CBPeripheral, advertisedName: String?) {
        self.id = peripheral.identifier
        self.peripheral = peripheral
        self.displayName = advertisedName ?? peripheral.name ?? "Sophon (unnamed)"
    }

    /// Inter-arrival time beyond which a sequence jump is read as the stream
    /// having been *interrupted* rather than frames having been *lost*.
    ///
    /// This is a threshold because nothing better exists. From the frame data
    /// alone the two cases are identical: whether three frames were lost on a
    /// live link or the app was suspended for an hour, the board carried on and
    /// `t_ms` advanced in proportion to wall time either way. No ratio separates
    /// them — only the size of the hole.
    ///
    /// 5 s is chosen against the rate that matters. At the board's ~54 Hz it is ~270
    /// frames, which is unambiguously an interruption rather than the
    /// scheduling jitter #211 exists to measure. At the skeleton's 1 Hz it is
    /// only 5 frames, so a genuine five-second dropout on a live link is
    /// misclassified as an interruption. That error is deliberate and one-sided:
    /// it under-counts loss slightly, where the previous behaviour over-counted
    /// it by thousands.
    private static let interruptionThreshold: TimeInterval = 5

    /// True once the motion characteristic has actually been subscribed — i.e.
    /// once there is a real Sophon on the other end, not merely a link.
    ///
    /// Core Bluetooth's `didConnect` says a connection exists, which between two
    /// iOS devices on one Apple ID can succeed against a phone whose Sophon app
    /// is closed. Presenting that as "Connected" claims a session that does not
    /// exist, so the UI waits for this instead.
    private(set) var hasSession = false

    /// When the current link was established. Needed so a device that has just
    /// connected, and legitimately has no frames yet, is not reported as stalled
    /// the instant it appears.
    private(set) var connectedAt: Date?

    /// How the link should be *described*, which is not the same as `state`.
    ///
    /// `state` reports what Core Bluetooth says about the connection, and Core
    /// Bluetooth is not wrong -- but it cannot know a peripheral has died until
    /// the supervision timeout expires. Measured against a SIGKILLed peripheral,
    /// frames stopped instantly while `didDisconnectPeripheral` took another 49
    /// seconds; between two iOS devices on one Apple ID, where the system keeps
    /// its own links up, it has been observed to take minutes.
    ///
    /// So a live link is not evidence of a live stream, and this app must not
    /// present it as though it were. That is the same discipline the `seq` rules
    /// apply to the data, applied one layer up to the link.
    ///
    /// Deliberately NOT a synthesised disconnect: during that window the
    /// connection really is open, and faking a close would both misreport the
    /// radio and destroy the transmit-counter baselines.
    enum LinkStatus: Equatable {
        case discovered
        case connecting
        case connected
        /// Connected, but nothing has arrived for `silentFor`.
        case stalled(silentFor: TimeInterval)
        case disconnected
        /// Disconnected because the user asked for it, and staying that way.
        /// `silentFor` is how long since an advertisement was last heard, so a
        /// released board that is still on the air can be told from one that has
        /// been taken by someone else.
        ///
        /// Distinct from `disconnected` because the two mean opposite things to a
        /// reader: one is something going wrong, the other is the app doing as it
        /// was told. Reporting a deliberate release in red as a fault would be the
        /// same category of lie this type exists to avoid.
        case released(silentFor: TimeInterval)
    }

    /// Takes `now` explicitly so the caller controls when this is re-evaluated --
    /// a view can drive it from a timeline and get a value that actually changes,
    /// rather than one frozen at whenever the body last happened to run.
    ///
    /// **No default on purpose (#242).** A default of `Date()` let three call
    /// sites read this at body-evaluation time without it being visible in
    /// review, and the failure is silent: during a stall nothing observable on
    /// this object changes, so those bodies were never re-evaluated and the text
    /// written to explain a stall could not render during one. Requiring the
    /// argument makes a body-time read something you have to type.
    func linkStatus(asOf now: Date) -> LinkStatus {
        // Checked before `state`, because a released board sits in `.disconnected`
        // and would otherwise be indistinguishable from one that dropped out.
        if isReleasedByUser, !state.isConnected {
            return .released(silentFor: lastSeenAt.map { now.timeIntervalSince($0) } ?? .infinity)
        }

        switch state {
        case .discovered: return .discovered
        case .connecting: return .connecting
        case .disconnected: return .disconnected
        case .connected:
            // A link without a subscribed characteristic is not a session. Report
            // it as still trying rather than as connected, so a phantom link to a
            // phone with no Sophon running never flashes up as success.
            guard hasSession else { return .connecting }

            // Falls back to the session start, so "subscribed and never sent
            // anything" is also caught rather than waiting forever on a first
            // frame that is not coming.
            guard let since = lastFrameAt ?? connectedAt else { return .connected }
            let silent = now.timeIntervalSince(since)
            return silent > Self.interruptionThreshold ? .stalled(silentFor: silent) : .connected
        }
    }

    func ingest(_ frame: MotionFrame) {
        let now = Date()

        if let previous = previousFrame, frame.tMillis < previous.tMillis {
            // Uptime went backwards, so the peripheral restarted while the link
            // stayed up. Its seq and its transmit counters both restart from
            // zero, which makes every comparison against the old session
            // meaningless -- the sequence jump is not loss, and `sent` would
            // appear to run backwards.
            //
            // MEASURED CORRECTION, and worth reading before relying on this.
            //
            // This branch was justified by the claim that a quick power cycle
            // stays inside the supervision timeout, so iOS never reports a
            // disconnect, making uptime the only reliable signal. That is not
            // what hardware does. Pressing reset on the board never reaches
            // here: the SoC loses its connection state entirely, so it stops
            // servicing connection events, the central's supervision timeout
            // expires, and the board is picked up again through a normal
            // reconnect -- beginSession(), not this path. Confirmed on the
            // board across repeated resets, with this counter staying at 0.
            //
            // A peripheral cannot hold a link it has forgotten. So for real
            // hardware the reliable signal is the reconnect itself.
            //
            // The branch is kept because it is cheap and correct when it does
            // fire, and it is reachable: a peripheral that restarts its
            // *application* state without dropping the link lands here. The
            // simulator's Reboot button is currently the only such thing, and
            // exists precisely to exercise this.
            noteBoardRestart()
        } else if let previous = previousFrame {
            let missing = max(0, frame.gap(since: previous))
            if missing > 0 {
                let elapsed = lastFrameAt.map { now.timeIntervalSince($0) } ?? 0
                // Two independent signals, because each covers the other's
                // blind spot. The lifecycle flag is exact but only fires when
                // iOS actually backgrounds the app; the elapsed-time threshold
                // catches long holes that arrive some other way -- delivery
                // throttling, a stall -- where no notification was posted.
                if wasSuspended || elapsed > Self.interruptionThreshold {
                    // Not loss. The frames were sent; this app was not there to
                    // receive them — a locked phone suspends the app while the
                    // BLE link itself stays up, so no disconnect resets anything.
                    interruptions += 1
                    framesDuringInterruptions += missing
                } else {
                    seqGaps += missing
                }
            }
        }

        previousFrame = frame
        lastFrame = frame
        lastFrameAt = now
        framesReceived += 1
        wasSuspended = false
    }

    /// Called when iOS backgrounds the app. The next frame to arrive will treat
    /// its gap as an interruption rather than loss, however short it was.
    func noteSuspended() {
        wasSuspended = true
    }

    /// The peripheral rebooted underneath a link that never dropped.
    ///
    /// Everything session-scoped is cleared, because the board's own figures just
    /// went back to zero: its `seq`, its uptime and its transmit counters all
    /// restart from boot. Keeping the app's running totals across that boundary
    /// left the detail view comparing two different intervals -- the transmit
    /// counters rebased onto the new boot while `framesReceived` still spanned
    /// both -- and the attribution sentence is built on exactly that comparison.
    ///
    /// It also makes the display independent of which path ran. A board reset
    /// always comes back through `beginSession()` (see the note in `ingest`);
    /// an application-level restart on a live link reaches here. Those should
    /// not read differently to someone watching the screen, and now they do not
    /// -- both leave the counters fresh.
    ///
    /// Deliberately NOT resetLinkStats():
    ///   - `restartsWithoutDisconnect` has to survive, and be incremented -- it is the record
    ///     that this happened at all, and resetLinkStats() would zero it;
    ///   - `attMTU` has to survive, because the *connection* did. The MTU was
    ///     negotiated before the reboot and is still in force.
    ///
    /// No sequence gap is counted for the frame that triggers this: the jump is a
    /// new boot's numbering, not loss. The caller assigns `previousFrame` at the
    /// end of `ingest`, making this frame the start of the new comparison.
    private func noteBoardRestart() {
        restartsWithoutDisconnect += 1

        framesReceived = 0
        seqGaps = 0
        interruptions = 0
        framesDuringInterruptions = 0
        previousFrame = nil

        // The next read re-establishes the baseline; until then `lostOnAir`
        // reports nil rather than a figure spanning two boots.
        txStats = nil
        txStatsAtConnect = nil
        txStatsAt = nil

        // Staleness is measured from here, since this is where the new session
        // begins as far as the data is concerned.
        connectedAt = Date()
    }

    /// Begins a session: a real Sophon has been found behind the link.
    ///
    /// Idempotent, because it resets the counters. `didDiscoverServices` is
    /// normally called once per connection, but iOS may report services again
    /// mid-connection, and a second call must not wipe a session in progress.
    func beginSession() {
        guard !hasSession else { return }
        hasSession = true
        resetLinkStats()

        // Re-established AFTER the reset, which clears it. The MTU is a property
        // of the connection, and the connection is older than the session -- it
        // was negotiated back at didConnect. Letting resetLinkStats() clear it
        // and leaving it cleared silently dropped the ATT MTU row from the
        // detail view once the reset moved out of didConnect.
        attMTU = peripheral.maximumWriteValueLength(for: .withoutResponse) + 3
    }

    /// Ends it. The counters are deliberately left alone so the record of what
    /// just happened survives on screen for reading.
    func endSession() {
        hasSession = false
    }

    /// Clears everything scoped to **one session**, leaving advertisement-scoped
    /// state alone.
    ///
    /// Called from `beginSession()`, **not** from `didConnect`. A connection is
    /// not a session: #228 established that a link can come up to a peripheral
    /// that is not running Sophon at all, so the counters start only once a
    /// Sophon service has been confirmed. An earlier version of this comment said
    /// they reset "when a new connection starts", which undoes that distinction.
    ///
    /// `identity` and `txPower` are deliberately absent — their lifetime is the
    /// advertisement, and nothing re-delivers one on demand (#230). `attMTU` is
    /// cleared here and immediately re-established by `beginSession()`, because
    /// the connection is older than the session.
    func resetLinkStats() {
        connectedAt = Date()
        framesReceived = 0
        seqGaps = 0
        interruptions = 0
        framesDuringInterruptions = 0
        restartsWithoutDisconnect = 0
        previousFrame = nil
        lastFrame = nil
        lastFrameAt = nil
        attMTU = nil
        linkParams = nil
        linkParamsRequestedAt = nil
        // offersLinkParams is deliberately NOT cleared here. It describes the
        // peripheral's GATT database, which is stable across a reconnect, and
        // latching it is what keeps the three rows on screen through this very
        // reset instead of flashing out and back -- the same rule that latches
        // displayName and identity against a callback carrying nothing.
        //
        // The trade is a stale answer if a board is reflashed across #224 within
        // one app run. It costs one round trip: every connection re-enumerates
        // characteristics and overwrites this, and a stale `false` hides rows
        // rather than showing wrong ones.
        txStats = nil
        txStatsAtConnect = nil
        txStatsAt = nil
        seqGapsAtStatsRead = 0
    }

    func ingest(_ stats: TxStats) {
        // The first read of a connection becomes the baseline, so the UI can
        // report what happened during this session. The board's totals survive
        // reconnects; this app's counters do not, and comparing the two without
        // a baseline would be misleading.
        if txStatsAtConnect == nil {
            txStatsAtConnect = stats
        }
        txStats = stats
        txStatsAt = Date()

        // Paired with the counters that just arrived, not read later. Both terms
        // of lostOnAir then cover connect -> this read.
        seqGapsAtStatsRead = seqGaps
    }

    /// Board-side counters scoped to **this connection**, which is the only form
    /// comparable with `framesReceived` and `seqGaps`.
    ///
    /// The board's own totals are cumulative since it booted and survive a
    /// reconnect; this app's counters reset on every connect. Showing the two
    /// side by side without rebasing invites a false reading — `sent` would
    /// simply be larger than `received` by however long the board had been
    /// running beforehand.
    var txThisSession: (sent: UInt32, noBuffer: UInt32, other: UInt32)? {
        guard let now = txStats, let base = txStatsAtConnect else { return nil }
        return (now.sent &- base.sent,
                now.noBuffer &- base.noBuffer,
                now.other &- base.other)
    }

    /// Frames that were produced and never arrived, excluding the ones the
    /// peripheral dropped before they reached the air.
    ///
    /// **As of the last stats read, not as of now** -- which is the whole point.
    /// `seqGaps` counts holes in the sequence; `noBuffer` counts sends the
    /// peripheral itself refused. Subtracting leaves what was handed to the radio
    /// and lost, but only if both counts cover the same window.
    ///
    /// Two earlier versions of this got it wrong in the same way. The first
    /// computed `sent - received`, two values sampled on different clocks. The
    /// second -- this one until #247 -- switched to event counts and claimed that
    /// "sidesteps the question entirely", which was half right: counting events
    /// removes the instantaneous-sampling problem but not the WINDOW MISMATCH.
    /// `seqGaps` advanced as frames arrived while `noBuffer` sat up to a poll
    /// behind, so the difference climbed for two seconds and collapsed when a
    /// fresh read landed. Measured on an iOS-to-iOS link: a sawtooth to about 20
    /// and back to zero, over and over, reading exactly like intermittent air
    /// loss when the true value was zero.
    ///
    /// So `seqGaps` is snapshotted in `ingest(_:)` alongside the counters it will
    /// be differenced against. The figure now moves once per poll rather than
    /// continuously, which is honest: it is a statement about the last read.
    var lostOnAir: Int? {
        guard let tx = txThisSession else { return nil }
        return max(0, seqGapsAtStatsRead - Int(tx.noBuffer))
    }
}
