import CoreBluetooth
import Foundation

/// One Sophon board.
///
/// Deliberately split from ``SophonHub``: an app gets exactly one
/// `CBCentralManager`, so it cannot live on a per-device object. Keeping
/// per-device state here means views bind to a device rather than to a global,
/// and a second board needs no restructuring.
@MainActor
@Observable
final class SophonDevice: Identifiable {
    enum State: Equatable {
        case discovered
        case connecting
        case connected
        case disconnected(reason: String?)

        var isConnected: Bool { self == .connected }
    }

    /// `CBPeripheral.identifier` — generated by iOS, stable per phone, but
    /// different on a different phone. Not the board's own identity.
    let id: UUID
    let peripheral: CBPeripheral

    /// From the scan-response name, e.g. `Sophon-A3F2`. This *is* the board's
    /// own identity, derived from its FICR chip id.
    var displayName: String

    var state: State = .discovered
    var rssi: Int?

    // Link health. These are in the skeleton rather than deferred because they
    // are what turn "does it still work with 4 boards?" into an observation
    // instead of a guess (#211).
    var framesReceived: Int = 0
    /// Frames the board sent, on a live stream, that never arrived. Excludes
    /// anything missed while this app was not listening — see `interruptions`.
    var seqGaps: Int = 0
    /// Times the stream resumed after a hole too large to be loss. Surfaced
    /// separately rather than silently discarded: "gaps 0, interruptions 3"
    /// says more than either number alone, and hiding the interruption would
    /// make a suspended app look like a flawless link.
    var interruptions: Int = 0
    /// Frames unaccounted for across those interruptions. Not losses, but not
    /// nothing either — this is the data the app did not see.
    var framesDuringInterruptions: Int = 0
    /// Times the board restarted mid-connection. Detected exactly rather than
    /// guessed: the frame's `t_ms` is board uptime, so a value lower than the
    /// previous one can only mean it rebooted.
    /// Times the peripheral restarted **without the link dropping**, detected
    /// from `t_ms` running backwards.
    ///
    /// Not a count of peripheral restarts in general, which is why it is not
    /// named for one. A board reset loses the SoC's connection state, so it
    /// comes back as a reconnect and never reaches the detector -- measured at
    /// 0 across repeated resets. See the note in `ingest`.
    var restartsWithoutDisconnect: Int = 0
    var lastFrame: MotionFrame?
    var lastFrameAt: Date?

    /// Negotiated on connect. Expect 23 — logged rather than assumed, on both sides.
    var attMTU: Int?

    /// The board's own transmit counters, read over the stats characteristic.
    /// Cumulative since the *board's* boot, so they do not reset when this
    /// connection does — which is why `txStatsAtConnect` is kept alongside.
    var txStats: TxStats?
    /// Snapshot taken on connect, so the UI can show movement during this
    /// session rather than a total that is mostly historical.
    var txStatsAtConnect: TxStats?
    var txStatsAt: Date?
    /// framesReceived at the instant the stats baseline was taken, so both
    /// sides of the comparison start from the same moment.
    private var framesAtStatsBaseline: Int = 0
    /// Same idea for interruption frames, so a hole that predates the
    /// baseline is not subtracted from a window it never belonged to.
    private var interruptedFramesAtStatsBaseline: Int = 0

    private var previousFrame: MotionFrame?
    /// Set when iOS reports the app left the foreground, cleared by the next
    /// frame that arrives. Any gap spanning it is an interruption regardless of
    /// how brief it was -- which is what elapsed time alone cannot tell you.
    private var wasSuspended = false

    init(peripheral: CBPeripheral, advertisedName: String?) {
        self.id = peripheral.identifier
        self.peripheral = peripheral
        self.displayName = advertisedName ?? peripheral.name ?? "Sophon (unnamed)"
    }

    /// Inter-arrival time beyond which a sequence jump is read as the stream
    /// having been *interrupted* rather than frames having been *lost*.
    ///
    /// This is a threshold because nothing better exists. From the frame data
    /// alone the two cases are identical: whether three frames were lost on a
    /// live link or the app was suspended for an hour, the board carried on and
    /// `t_ms` advanced in proportion to wall time either way. No ratio separates
    /// them — only the size of the hole.
    ///
    /// 5 s is chosen against the rate that matters. At #209's 50 Hz it is 250
    /// frames, which is unambiguously an interruption rather than the
    /// scheduling jitter #211 exists to measure. At the skeleton's 1 Hz it is
    /// only 5 frames, so a genuine five-second dropout on a live link is
    /// misclassified as an interruption. That error is deliberate and one-sided:
    /// it under-counts loss slightly, where the previous behaviour over-counted
    /// it by thousands.
    private static let interruptionThreshold: TimeInterval = 5

    /// True once the motion characteristic has actually been subscribed — i.e.
    /// once there is a real Sophon on the other end, not merely a link.
    ///
    /// Core Bluetooth's `didConnect` says a connection exists, which between two
    /// iOS devices on one Apple ID can succeed against a phone whose Sophon app
    /// is closed. Presenting that as "Connected" claims a session that does not
    /// exist, so the UI waits for this instead.
    private(set) var hasSession = false

    /// When the current link was established. Needed so a device that has just
    /// connected, and legitimately has no frames yet, is not reported as stalled
    /// the instant it appears.
    private(set) var connectedAt: Date?

    /// How the link should be *described*, which is not the same as `state`.
    ///
    /// `state` reports what Core Bluetooth says about the connection, and Core
    /// Bluetooth is not wrong -- but it cannot know a peripheral has died until
    /// the supervision timeout expires. Measured against a SIGKILLed peripheral,
    /// frames stopped instantly while `didDisconnectPeripheral` took another 49
    /// seconds; between two iOS devices on one Apple ID, where the system keeps
    /// its own links up, it has been observed to take minutes.
    ///
    /// So a live link is not evidence of a live stream, and this app must not
    /// present it as though it were. That is the same discipline the `seq` rules
    /// apply to the data, applied one layer up to the link.
    ///
    /// Deliberately NOT a synthesised disconnect: during that window the
    /// connection really is open, and faking a close would both misreport the
    /// radio and destroy the transmit-counter baselines.
    enum LinkStatus: Equatable {
        case discovered
        case connecting
        case connected
        /// Connected, but nothing has arrived for `silentFor`.
        case stalled(silentFor: TimeInterval)
        case disconnected
    }

    /// Takes `now` explicitly so the caller controls when this is re-evaluated --
    /// a view can drive it from a timeline and get a value that actually changes,
    /// rather than one frozen at whenever the body last happened to run.
    func linkStatus(asOf now: Date = Date()) -> LinkStatus {
        switch state {
        case .discovered: return .discovered
        case .connecting: return .connecting
        case .disconnected: return .disconnected
        case .connected:
            // A link without a subscribed characteristic is not a session. Report
            // it as still trying rather than as connected, so a phantom link to a
            // phone with no Sophon running never flashes up as success.
            guard hasSession else { return .connecting }

            // Falls back to the session start, so "subscribed and never sent
            // anything" is also caught rather than waiting forever on a first
            // frame that is not coming.
            guard let since = lastFrameAt ?? connectedAt else { return .connected }
            let silent = now.timeIntervalSince(since)
            return silent > Self.interruptionThreshold ? .stalled(silentFor: silent) : .connected
        }
    }

    func ingest(_ frame: MotionFrame) {
        let now = Date()

        if let previous = previousFrame, frame.tMillis < previous.tMillis {
            // Uptime went backwards, so the peripheral restarted while the link
            // stayed up. Its seq and its transmit counters both restart from
            // zero, which makes every comparison against the old session
            // meaningless -- the sequence jump is not loss, and `sent` would
            // appear to run backwards.
            //
            // MEASURED CORRECTION, and worth reading before relying on this.
            //
            // This branch was justified by the claim that a quick power cycle
            // stays inside the supervision timeout, so iOS never reports a
            // disconnect, making uptime the only reliable signal. That is not
            // what hardware does. Pressing reset on the board never reaches
            // here: the SoC loses its connection state entirely, so it stops
            // servicing connection events, the central's supervision timeout
            // expires, and the board is picked up again through a normal
            // reconnect -- beginSession(), not this path. Confirmed on the
            // board across repeated resets, with this counter staying at 0.
            //
            // A peripheral cannot hold a link it has forgotten. So for real
            // hardware the reliable signal is the reconnect itself.
            //
            // The branch is kept because it is cheap and correct when it does
            // fire, and it is reachable: a peripheral that restarts its
            // *application* state without dropping the link lands here. The
            // simulator's Reboot button is currently the only such thing, and
            // exists precisely to exercise this.
            noteBoardRestart()
        } else if let previous = previousFrame {
            let missing = max(0, frame.gap(since: previous))
            if missing > 0 {
                let elapsed = lastFrameAt.map { now.timeIntervalSince($0) } ?? 0
                // Two independent signals, because each covers the other's
                // blind spot. The lifecycle flag is exact but only fires when
                // iOS actually backgrounds the app; the elapsed-time threshold
                // catches long holes that arrive some other way -- delivery
                // throttling, a stall -- where no notification was posted.
                if wasSuspended || elapsed > Self.interruptionThreshold {
                    // Not loss. The frames were sent; this app was not there to
                    // receive them — a locked phone suspends the app while the
                    // BLE link itself stays up, so no disconnect resets anything.
                    interruptions += 1
                    framesDuringInterruptions += missing
                } else {
                    seqGaps += missing
                }
            }
        }

        previousFrame = frame
        lastFrame = frame
        lastFrameAt = now
        framesReceived += 1
        wasSuspended = false
    }

    /// Called when iOS backgrounds the app. The next frame to arrive will treat
    /// its gap as an interruption rather than loss, however short it was.
    func noteSuspended() {
        wasSuspended = true
    }

    /// Counters describe one connection, so they reset when a new one starts —
    /// otherwise a gap is counted across a disconnect, where a sequence jump is
    /// expected rather than a dropped frame.
    /// The board rebooted underneath a link that never dropped.
    ///
    /// Everything session-scoped is cleared, because the board's own figures just
    /// went back to zero: its `seq`, its uptime and its transmit counters all
    /// restart from boot. Keeping the app's running totals across that boundary
    /// left the detail view comparing two different intervals -- the transmit
    /// counters rebased onto the new boot while `framesReceived` still spanned
    /// both -- and the attribution sentence is built on exactly that comparison.
    ///
    /// It also makes the display independent of which path ran. A board reset
    /// always comes back through `beginSession()` (see the note in `ingest`);
    /// an application-level restart on a live link reaches here. Those should
    /// not read differently to someone watching the screen, and now they do not
    /// -- both leave the counters fresh.
    ///
    /// Deliberately NOT resetLinkStats():
    ///   - `restartsWithoutDisconnect` has to survive, and be incremented -- it is the record
    ///     that this happened at all, and resetLinkStats() would zero it;
    ///   - `attMTU` has to survive, because the *connection* did. The MTU was
    ///     negotiated before the reboot and is still in force.
    ///
    /// No sequence gap is counted for the frame that triggers this: the jump is a
    /// new boot's numbering, not loss. The caller assigns `previousFrame` at the
    /// end of `ingest`, making this frame the start of the new comparison.
    private func noteBoardRestart() {
        restartsWithoutDisconnect += 1

        framesReceived = 0
        seqGaps = 0
        interruptions = 0
        framesDuringInterruptions = 0
        previousFrame = nil

        // The next read re-establishes the baseline; until then `lostOnAir`
        // reports nil rather than a figure spanning two boots.
        txStats = nil
        txStatsAtConnect = nil
        txStatsAt = nil

        // Staleness is measured from here, since this is where the new session
        // begins as far as the data is concerned.
        connectedAt = Date()
    }

    /// Begins a session: a real Sophon has been found behind the link.
    ///
    /// Idempotent, because it resets the counters. `didDiscoverServices` is
    /// normally called once per connection, but iOS may report services again
    /// mid-connection, and a second call must not wipe a session in progress.
    func beginSession() {
        guard !hasSession else { return }
        hasSession = true
        resetLinkStats()

        // Re-established AFTER the reset, which clears it. The MTU is a property
        // of the connection, and the connection is older than the session -- it
        // was negotiated back at didConnect. Letting resetLinkStats() clear it
        // and leaving it cleared silently dropped the ATT MTU row from the
        // detail view once the reset moved out of didConnect.
        attMTU = peripheral.maximumWriteValueLength(for: .withoutResponse) + 3
    }

    /// Ends it. The counters are deliberately left alone so the record of what
    /// just happened survives on screen for reading.
    func endSession() {
        hasSession = false
    }

    func resetLinkStats() {
        connectedAt = Date()
        framesReceived = 0
        seqGaps = 0
        interruptions = 0
        framesDuringInterruptions = 0
        restartsWithoutDisconnect = 0
        previousFrame = nil
        lastFrame = nil
        lastFrameAt = nil
        attMTU = nil
        txStats = nil
        txStatsAtConnect = nil
        txStatsAt = nil
        framesAtStatsBaseline = 0
        interruptedFramesAtStatsBaseline = 0
    }

    func ingest(_ stats: TxStats) {
        // The first read of a connection becomes the baseline, so the UI can
        // report what happened during this session. The board's totals survive
        // reconnects; this app's counters do not, and comparing the two without
        // a baseline would be misleading.
        //
        // framesReceived is snapshotted at the same instant. That read lands a
        // second or two after connect — after service and characteristic
        // discovery — and any frames arriving in that window are already inside
        // the board's baseline while still counted by this app. Without pinning
        // both to the same moment, the session figures drift apart by exactly
        // the number of frames that slipped through the gap.
        if txStatsAtConnect == nil {
            txStatsAtConnect = stats
            framesAtStatsBaseline = framesReceived
            interruptedFramesAtStatsBaseline = framesDuringInterruptions
        }
        txStats = stats
        txStatsAt = Date()
    }

    /// Board-side counters scoped to **this connection**, which is the only form
    /// comparable with `framesReceived` and `seqGaps`.
    ///
    /// The board's own totals are cumulative since it booted and survive a
    /// reconnect; this app's counters reset on every connect. Showing the two
    /// side by side without rebasing invites a false reading — `sent` would
    /// simply be larger than `received` by however long the board had been
    /// running beforehand.
    var txThisSession: (sent: UInt32, noBuffer: UInt32, other: UInt32)? {
        guard let now = txStats, let base = txStatsAtConnect else { return nil }
        return (now.sent &- base.sent,
                now.noBuffer &- base.noBuffer,
                now.other &- base.other)
    }

    /// Frames that were produced and never arrived, excluding the ones the
    /// board dropped before they reached the air.
    ///
    /// Derived from two **event counts over the same window**, not from two
    /// snapshots taken at different instants. `seqGaps` counts holes in the
    /// sequence; `noBuffer` counts sends the board itself refused. Subtracting
    /// leaves what was handed to the radio and lost.
    ///
    /// The earlier version computed `sent - received`, which cannot work:
    /// those two are sampled on different clocks, so at read time the board has
    /// usually just sent a frame the app has not decoded yet. Reading them a
    /// poll apart only traded the resulting flicker for a permanent zero.
    /// Counting events sidesteps the question entirely -- neither term is an
    /// instantaneous reading.
    var lostOnAir: Int? {
        guard let tx = txThisSession else { return nil }
        return max(0, seqGaps - Int(tx.noBuffer))
    }
}
