import CoreBluetooth
import Foundation

/// One Sophon board.
///
/// Deliberately split from ``SophonHub``: an app gets exactly one
/// `CBCentralManager`, so it cannot live on a per-device object. Keeping
/// per-device state here means views bind to a device rather than to a global,
/// and a second board needs no restructuring.
@MainActor
@Observable
final class SophonDevice: Identifiable {
    enum State: Equatable {
        case discovered
        case connecting
        case connected
        case disconnected(reason: String?)

        var isConnected: Bool { self == .connected }
    }

    /// `CBPeripheral.identifier` — generated by iOS, stable per phone, but
    /// different on a different phone. Not the board's own identity.
    let id: UUID
    let peripheral: CBPeripheral

    /// From the scan-response name, e.g. `Sophon-A3F2`. This *is* the board's
    /// own identity, derived from its FICR chip id.
    var displayName: String

    var state: State = .discovered
    var rssi: Int?

    // Link health. These are in the skeleton rather than deferred because they
    // are what turn "does it still work with 4 boards?" into an observation
    // instead of a guess (#211).
    var framesReceived: Int = 0
    var seqGaps: Int = 0
    var lastFrame: MotionFrame?
    var lastFrameAt: Date?

    /// Negotiated on connect. Expect 23 — logged rather than assumed, on both sides.
    var attMTU: Int?

    private var previousFrame: MotionFrame?

    init(peripheral: CBPeripheral, advertisedName: String?) {
        self.id = peripheral.identifier
        self.peripheral = peripheral
        self.displayName = advertisedName ?? peripheral.name ?? "Sophon (unnamed)"
    }

    func ingest(_ frame: MotionFrame) {
        if let previous = previousFrame {
            seqGaps += max(0, frame.gap(since: previous))
        }
        previousFrame = frame
        lastFrame = frame
        lastFrameAt = Date()
        framesReceived += 1
    }

    /// Counters describe one connection, so they reset when a new one starts —
    /// otherwise a gap is counted across a disconnect, where a sequence jump is
    /// expected rather than a dropped frame.
    func resetLinkStats() {
        framesReceived = 0
        seqGaps = 0
        previousFrame = nil
        lastFrame = nil
        lastFrameAt = nil
        attMTU = nil
    }
}
