$kind: http-request
url: https://api.digikey.com/products/v4/search/{{part_number}}/productdetails
method: GET
headers:
  Authorization: Bearer {{access_token}}
  X-DIGIKEY-Client-Id: "{{client_id}}"
  X-DIGIKEY-Locale-Language: "{{locale_language}}"
  X-DIGIKEY-Locale-Site: "{{locale_site}}"
  X-DIGIKEY-Locale-Currency: "{{locale_currency}}"
order: 3000
