#!/bin/sh
#
# Generates ios/FirstContact/FirstContact/GeneratedSecrets.swift from build
# settings injected by Secrets.xcconfig. Wired in via a PBXShellScriptBuildPhase
# in project.pbxproj that runs BEFORE the Compile Sources phase.
#
# The generated file is gitignored — its content is regenerated on every
# build, so the secret value lives only on the machine that built it.
#
# If Secrets.xcconfig is missing or a key is unset, this script still emits a
# valid Swift file with empty-string values — the app renders the setup-hint
# state (LAST 30 DAYS panel / news screen) and stays building.

set -eu

OUTPUT="${SRCROOT}/FirstContact/GeneratedSecrets.swift"

# Escape backslashes and double-quotes for safe embedding in a Swift string
# literal. Keys are typically alphanumeric + `-` / `_`, but the sed pass keeps
# us safe if anyone ever pastes something exotic.
escape() { printf '%s' "${1}" | sed 's/\\/\\\\/g; s/"/\\"/g'; }

# Pull keys from the build env (set by xcconfig). Default to empty.
GEMINI_ESCAPED=$(escape "${GEMINI_API_KEY:-}")
GNEWS_ESCAPED=$(escape "${GNEWS_API_KEY:-}")

cat > "${OUTPUT}" <<SWIFT
// Auto-generated by ios/FirstContact/scripts/generate-secrets.sh.
// DO NOT EDIT. The values are injected from Secrets.xcconfig at build time.
// This file is gitignored — it never reaches the repo.

enum GeneratedSecrets {
    static let geminiAPIKey = "${GEMINI_ESCAPED}"
    static let gnewsAPIKey = "${GNEWS_ESCAPED}"
}
SWIFT
