#!/bin/sh
#
# Generates ios/FirstContact/FirstContact/GeneratedSecrets.swift from build
# settings injected by Secrets.xcconfig. Wired in via a PBXShellScriptBuildPhase
# in project.pbxproj that runs BEFORE the Compile Sources phase.
#
# The generated file is gitignored — its content is regenerated on every
# build, so the secret value lives only on the machine that built it.
#
# If Secrets.xcconfig is missing or GEMINI_API_KEY is unset, this script
# still emits a valid Swift file with an empty-string value — the app
# renders the setup-hint state in the LAST 30 DAYS panel and stays building.

set -eu

OUTPUT="${SRCROOT}/FirstContact/GeneratedSecrets.swift"

# Pull the key from the build env (set by xcconfig). Default to empty.
KEY="${GEMINI_API_KEY:-}"

# Escape any backslashes and double-quotes for safe embedding in a Swift
# string literal. AI Studio keys are typically alphanumeric + `-` / `_`,
# but the sed pass keeps us safe if anyone ever pastes something exotic.
ESCAPED=$(printf '%s' "${KEY}" | sed 's/\\/\\\\/g; s/"/\\"/g')

cat > "${OUTPUT}" <<SWIFT
// Auto-generated by ios/FirstContact/scripts/generate-secrets.sh.
// DO NOT EDIT. The value is injected from Secrets.xcconfig at build time.
// This file is gitignored — it never reaches the repo.

enum GeneratedSecrets {
    static let geminiAPIKey = "${ESCAPED}"
}
SWIFT
