# Writes the build timestamp into a generated header.
#
# Run as `cmake -P` from an add_custom_command that re-runs on EVERY build, so
# the value tracks the build rather than the last configure.
#
# Deliberately not __DATE__/__TIME__: those record when one translation unit
# was compiled, so an incremental build that does not recompile that file
# prints a stale time -- claiming you had not flashed the new build when you
# had, which is worse than printing nothing.

string(TIMESTAMP SOPHON_BUILD_TIME "%Y-%m-%dT%H:%M:%SZ" UTC)

file(WRITE ${OUT_FILE}
"/* Generated by cmake/gen_build_time.cmake -- do not edit. */
#ifndef SOPHON_BUILD_TIME_H
#define SOPHON_BUILD_TIME_H

#define SOPHON_BUILD_TIME \"${SOPHON_BUILD_TIME}\"

#endif /* SOPHON_BUILD_TIME_H */
")
